use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'XCCommonKit_Example' do
  pod 'XCCommonKit', :path => '../'

  target 'XCCommonKit_Tests' do
    inherit! :search_paths

    
  end
end
